read("/home/ubuntu/code/math-modular-sources/lattice/sources_s18_zud/s18_setup.gp");
Z = x*deriv(U18/x)/(U18/x);
W = -F18*Z;
nc = 30;
wv = vector(nc+1, i, polcoeff(W, i-1));
print("W coeffs (0..",nc,"): ", wv);
print("--- M_2(Gamma_0(18)) : F18 and -Z ---");
mf2 = mfinit([18,2],4);
print("dim M_2(18) = ", mfdim(mf2));
fv = vector(nc+1,i,polcoeff(F18,i-1));
zv = vector(nc+1,i,polcoeff(-Z,i-1));
print("F18 in basis: ", mftobasis(mf2, fv));
print("-Z  in basis: ", mftobasis(mf2, zv));
print("--- M_4(Gamma_0(18)) ---");
mf4 = mfinit([18,4],4);
print("dim M_4(18) = ", mfdim(mf4));
co = mftobasis(mf4, wv);
print("W in basis: ", co);
print("residual: ", mfcoefs(mflinear(mf4,co), nc) - wv);
print("--- Eisenstein / cuspidal split of M_4(18) ---");
mf4E = mfinit([18,4],3); mf4S = mfinit([18,4],1);
print("dim Eis = ", mfdim(mf4E), "   dim cusp = ", mfdim(mf4S));
coE = mftobasis(mf4E, wv, 1);
print("W tobasis in Eisenstein space (flag): ", coE);
quit;
