/* 07_foldreg.gp -- overconvergence / decay rates at both real places. */
default(parisizemax, 20000000000);
default(realprecision, 700);
read("build.txt");
s5 = sqrt(5); ph5 = (11+5*s5)/2; phm5 = (5*s5-11)/2; t1 = phm5; t2 = -ph5;
Lchi(s) = 5^(-s)*(zetahurwitz(s,1/5) + I*zetahurwitz(s,2/5) - I*zetahurwitz(s,3/5) - zetahurwitz(s,4/5));
LL = Lchi(2); LR = real(LL); LI = imag(LL); z = zeta(2)/5;
xi = ph5*LI - LR; xip = -phm5*LI - LR;
Bnew  = vector(NA+1, i, B3[i] + ph5*B4[i]);
Bnewp = vector(NA+1, i, B3[i] - phm5*B4[i]);
print("=== growth of A_n ===");
for(j=0,2, my(n=NA-j); print("  |A_",n,"|^(1/n) = ", (1.0*A[n+1])^(1/n), "   phi^5 = ", ph5));
print("  n*t1^n*A_n at n=NA, NA-1: ", NA*t1^NA*A[NA+1], "  ", (NA-1)*t1^(NA-1)*A[NA]);
print("");
print("=== (a) overconvergence at t1 = phi^-5 ===");
rate(cv, nm) = my(n=NA); print("  ", nm, ":  |c_n|^(1/n) = ", abs(cv[n+1])^(1/n), "   c_n/c_{n-1} = ", cv[n+1]/cv[n]);
cD = vector(NA+1, i, BD[i] - z*A[i]);
cN = vector(NA+1, i, Bnew[i] - xi*A[i]);
rate(cD, "B_D - (zeta(2)/5) A ");
rate(cN, "B_new - xi A        ");
print("  target phi^-5 = ", phm5, "    (|t1|^-1 = ", 1/t1, ", |t2|^-1 = ", 1/ph5, ")");
print("  |c_n|^(1/n)/phi^-5 - 1 for B_D  : ", abs(cD[NA+1])^(1/NA)/phm5 - 1);
print("  |c_n|^(1/n)/phi^-5 - 1 for B_new: ", abs(cN[NA+1])^(1/NA)/phm5 - 1);
print("");
print("=== (c) the conjugate B_new' = sigma(B_new) = B3 - phi^-5 B4 ===");
print("  B_new'_n/A_n at n=200,150,100,50: ");
for(k=1,4, my(n=[200,150,100,50][k]); print("     n=",n,"  ", Bnewp[n+1]/A[n+1]));
dif(n) = Bnewp[n+1]/A[n+1] - Bnewp[n]/A[n];
print("  n*(r_n - r_{n-1}) at n=200,150,100,50: ");
for(k=1,4, my(n=[200,150,100,50][k]); print("     n=",n,"  ", n*dif(n)));
print("  predicted kappa = 2/(5*sqrt5) / (lim n t1^n A_n) = ", (2/(5*s5))/(NA*t1^NA*A[NA+1]));
print("");
print("  best-possible decay of B_new' - lambda A: test lambda = xi', 0, and the");
print("  two-parameter family B_new' - lambda A - mu B_D (mu chosen to kill nothing).");
gg(lam) = vector(NA+1, i, Bnewp[i] - lam*A[i]);
for(k=1,3, my(lam=[xip, 0, 3.2125][k]); my(g=gg(lam)); print("     lambda=", lam*1.0, "  |g_n|^(1/n) = ", abs(g[NA+1])^(1/NA)));
print("  phi^5 = ", ph5);
print("  (B_new'_n - lambda A_n) * t1^n * n / log(n), lambda = xi' :");
for(k=1,3, my(n=[200,150,100][k]); my(g=gg(xip)); print("     n=",n,"  ", g[n+1]*t1^n*n/log(n), "     2/(5 sqrt5) = ", 2/(5*s5)));
print("");
print("=== lindep certificate for xi ===");
default(realprecision, 200);
xi2 = ph5*LI - LR;
print("  lindep [xi,1,zeta(2),ReL,ImL,sqrt5,sqrt5*ReL,sqrt5*ImL] = ", lindep([xi2, 1, zeta(2), LR, LI, s5, s5*LR, s5*LI], 60));
print("  lindep [xi',1,zeta(2),ReL,ImL,sqrt5,sqrt5*ReL,sqrt5*ImL] = ", lindep([-phm5*LI-LR, 1, zeta(2), LR, LI, s5, s5*LR, s5*LI], 60));
quit;
