default(parisizemax, 30000000000);
default(realprecision, 60);
NA = 210;
NQ = 222;
ps4(n) = if(n%5==0, 0, if(n%5==1, 1, if(n%5==2, I, if(n%5==3, -I, -1))));
ps4b(n) = conj(ps4(n));
one(n) = 1;
leg5(n) = kronecker(n,5);
Ap(n) = sum(k=0,n, binomial(n,k)^2*binomial(n+k,k));
eis(ch1, ch2, nq) = sum(n=1, nq-1, sumdiv(n, d, ch1(n/d)*ch2(d)*d^2)*q^n) + O(q^nq);
Dinv2(s) = my(n=serprec(s,q)); sum(k=1,n-1, polcoeff(s,k)/k^2*q^k) + O(q^n);
peel2(Fs, xs, na, nq) = my(a=vector(na+1), G=Fs, xp=1+O(q^nq)); for(n=0, na, my(c=polcoeff(G,n)); a[n+1]=c; if(c!=0, G=G-c*xp); xp=xp*xs); a;
xs = q*prod(n=1, NQ-1, (1 - q^n + O(q^NQ))^(5*leg5(n)));
print("x = ", xs + O(q^9));
gettime();
Fs = sum(n=0, NA, Ap(n)*xs^n) + O(q^NQ);
print("Fs built, time ", gettime());
Achk = peel2(Fs, xs, NA, NQ);
print("peel check A_n: ", vector(6,i,Achk[i]));
P1 = eis(one,ps4,NQ); P2 = eis(one,ps4b,NQ); P3 = eis(ps4,one,NQ); P4 = eis(ps4b,one,NQ);
R1 = P1+P2; R2 = I*(P1-P2); R3 = P3+P4; R4 = I*(P3-P4);
PhiD = R1/2 + R2;
print("PhiD = ", PhiD + O(q^8));
print("R3 = ", R3 + O(q^8));
print("R4 = ", R4 + O(q^8));
BD  = peel2(Fs*Dinv2(PhiD), xs, NA, NQ);
print("BD done, time ", gettime());
B3v = peel2(Fs*Dinv2(R3), xs, NA, NQ);
print("B(R3) done, time ", gettime());
B4v = peel2(Fs*Dinv2(R4), xs, NA, NQ);
print("B(R4) done, time ", gettime());
print("BD head: ", vector(6,i,BD[i]));
print("B(R3) head: ", vector(6,i,B3v[i]));
print("B(R4) head: ", vector(6,i,B4v[i]));
ph = (1+sqrt(5))/2;
print("Apery limit BD_n/A_n at n=NA: ", BD[NA+1]*1.0/Achk[NA+1], "   zeta(2)/5 = ", zeta(2)/5);
print("Apery limit Bnew_n/A_n at n=NA: ", (B3v[NA+1]+ph^5*B4v[NA+1])*1.0/Achk[NA+1]);
print("target xi = 0.6556341888406567663309814138723994024111");
write("A_coeffs.txt", "A=" , Achk);
write("BD_coeffs.txt", "BD=", BD);
write("BR3_coeffs.txt", "BR3=", B3v);
write("BR4_coeffs.txt", "BR4=", B4v);
quit;
