default(parisize,"24G");
default(linewrap,0);
BASE="/tmp/claude-1000/-home-ubuntu-code-math-modular-sources/9a849c0a-95f8-4d19-b342-98033d0d9c03/scratchpad/zeta7/";
CN=read(concat(BASE,"cn.txt"));
DN=read(concat(BASE,"dn.txt"));
NC=900;
ND=400;
CR=0;
DR=0;
mkprimes(np)=my(v=List(),q=2^61);for(i=1,np,q=precprime(q-1);listput(v,q));Vec(v);
setP(p)=CR=vector(NC+1,i,lift(Mod(CN[i],p)));DR=vector(ND+1,i,lift(Mod(DN[i],p)));1;
bigM(r,D,p)=my(sz=(r+1)*(D+1),n1=NC-r,n2=ND-r-1,M1,M2);M1=matrix(n1,sz,a,b,my(j=(b-1)\(D+1),k=(b-1)%(D+1),nn=r+a);lift(Mod(nn,p)^k)*CR[nn-j+1]%p);M2=matrix(n2,sz,a,b,my(j=(b-1)\(D+1),k=(b-1)%(D+1),nn=r+a);(lift(Mod(nn+1,p)^k)*DR[nn+2-j]+lift(Mod(nn,p)^k)*DR[nn+1-j])%p);matconcat([M1;M2]);
rrefm(A)=my(m=matsize(A)[1],N=matsize(A)[2],rr=1,piv=List(),i,t);for(j=1,N,if(rr<=m,i=rr;while(i<=m&&A[i,j]==0,i++);if(i<=m,t=A[rr,];A[rr,]=A[i,];A[i,]=t;A[rr,]=A[rr,]/A[rr,j];for(k=1,m,if(k!=rr,A[k,]=A[k,]-A[k,j]*A[rr,]));listput(piv,j);rr++)));[A,Vec(piv)];
canon(r,D,p)=my(K=matker(bigM(r,D,p)*Mod(1,p)),res);if(#K==0,return([0,0]));res=rrefm(mattranspose(K));[lift(res[1]),res[2]];
prim(v)=my(dd=1,g=0);for(i=1,#v,dd=lcm(dd,denominator(v[i])));v=v*dd;for(i=1,#v,g=gcd(g,v[i]));if(g==0,return(v));v/g;
tovec2pol(v,r,D)=vector(r+1,jj,sum(k=0,D,v[(jj-1)*(D+1)+k+1]*n^k));
maxdig(v)=my(m=0);for(i=1,#v,m=max(m,#Str(abs(v[i]))));m;
chiof(v,r,D)=sum(jj=0,r,v[jj*(D+1)+D+1]*L^(r-jj));
setP(2^61-1);
z=canon(19,13,2^61-1);
print("constant-residual subspace at (19,13): dim = ",if(type(z[1])=="t_MAT",matsize(z[1])[1],0),"  pivots ",z[2]);
NPMAX=400;
ps=mkprimes(NPMAX);
ACC=0;
piv0=0;
QH=vector(NPMAX);
OKH=vector(NPMAX);
nstab=0;
gettime();
{for(i=1,NPMAX, setP(ps[i]); res=canon(19,13,ps[i]); if(i==1, piv0=res[2]; ACC=res[1]*Mod(1,ps[i]), if(res[2]!=piv0, error("pivot mismatch ",i)); ACC=chinese(ACC,res[1]*Mod(1,ps[i]))); Q=bestappr(ACC); OKH[i]=(type(Q)=="t_MAT"); if(OKH[i],QH[i]=Q); if(i>=4 && OKH[i] && OKH[i-3], if(QH[i]==QH[i-3], nstab=i; break)));}
print("stable at ",nstab," primes, t=",gettime());
v=prim(QH[nstab][1,]);
PV=tovec2pol(v,19,13);
print("max coeff digits: ",maxdig(v));
bad=0;
{for(nn=20,900, my(s=0); for(j=0,19,s=s+subst(PV[j+1],n,nn)*CN[nn-j+1]); if(s!=0,bad=bad+1));}
print("EXACT c-annihilation n=20..900 failures: ",bad);
RS=vector(381,i,my(nn=19+i,s=0);for(j=0,19,s=s+subst(PV[j+1],n,nn)*DN[nn-j+1]);s);
CST=RS[1]*(-1)^20;
allc=1;
{for(i=1,381, if(RS[i]!=(-1)^(19+i)*CST, allc=0));}
print("R_n = (-1)^n * C for all n=20..400 ? ",allc);
print("C = ",CST);
print("C factored: ",factor(CST));
print("chi content = ",content(chiof(v,19,13)));
print("chi/content factored: ",factor(chiof(v,19,13)/content(chiof(v,19,13))));
print("P_0 factored:");
print(factor(PV[1]));
write(concat(BASE,"rec_19_13_constres.gp"),Str("PV=",PV));
quit;
