default(parisize,"48G");
NQ=930;
NC=900;
et(k)=prod(m=1,NQ\k+1,1-'q^(k*m)+O('q^(NQ+2)));
gettime();
h=et(1)^3*et(4)*et(6)^2/(et(2)^2*et(3)*et(12)^3)/'q;
x=h/((h+3)*(h+4));
g=vector(NQ,m,sum(i=1,6,my(dv=[1,2,3,4,6,12][i],cv=[1,-572,11583,-36608,46332,-20736][i]);if(m%dv==0,cv*sigma(m\dv,7),0)));
Psi=sum(m=1,NQ,(g[m]/m^7)*'q^m)+O('q^(NQ+1));
Phi=sum(m=1,NQ,g[m]*'q^m)+O('q^(NQ+1));
U=Phi/('q*deriv(x,'q));
print("setup ",gettime());
Qx=serreverse(x+O('q^(NC+2)));
print("serreverse ",gettime());
A=subst(U+O('q^(NC+2)),'q,Qx);
print("subst U ",gettime());
PsiX=subst(Psi+O('q^(NC+2)),'q,Qx);
print("subst Psi ",gettime());
B=A*PsiX;
print("mult ",gettime());
dn=vector(NC+1,i,polcoeff(B,i-1));
write("dn900.txt",dn);
print("done. d_900 denominator digits: ",#Str(denominator(dn[NC+1])));
quit;
