default(parisize,"24G");
NQ=930;
NC=900;
et(k)=prod(m=1,NQ\k+1,1-'q^(k*m)+O('q^(NQ+2)));
gettime();
h=et(1)^3*et(4)*et(6)^2/(et(2)^2*et(3)*et(12)^3)/'q;
x=h/((h+3)*(h+4));
print("x precision: ",x);
print("h,x built: ",gettime()," ms");
g=vector(NQ,m,sum(i=1,6,my(dv=[1,2,3,4,6,12][i],cv=[1,-572,11583,-36608,46332,-20736][i]);if(m%dv==0,cv*sigma(m\dv,7),0)));
Phi=sum(m=1,NQ,g[m]*'q^m)+O('q^(NQ+1));
Psi=sum(m=1,NQ,(g[m]/m^7)*'q^m)+O('q^(NQ+1));
print("Phi,Psi built: ",gettime()," ms");
Dx='q*deriv(x,'q);
U=Phi/Dx;
print("U built: ",gettime()," ms  U=",U+O('q^6));
Qx=serreverse(x+O('q^(NC+2)));
print("serreverse: ",gettime()," ms");
A=subst(U+O('q^(NC+2)),'q,Qx);
print("subst U: ",gettime()," ms");
cn=vector(NC+1,i,polcoeff(A,i-1));
write("cn.txt",cn);
print("c_n written, n<=",NC,"  gettime ",gettime());
print("c_0..c_8 = ",vector(9,i,cn[i]));
print("all c_n integral n<=",NC,"? ",vecmax(vector(NC+1,i,denominator(cn[i])))==1);
print("log10|c_900| = ",log(abs(1.0*cn[NC+1]))/log(10));
print("signs c_n, n=890..900: ",vector(11,i,sign(cn[890+i])));
quit;
