default(parisize,"24G");
default(linewrap,0);
BASE="/tmp/claude-1000/-home-ubuntu-code-math-modular-sources/9a849c0a-95f8-4d19-b342-98033d0d9c03/scratchpad/zeta7/";
DN=read(concat(BASE,"dn900.txt"));
ND=900;
gettime();
chk(QV,r,nm)=my(R,S,W,ok=1,deg,DIF);R=vector(ND-r,i,my(nn=r+i,s=0);for(j=0,r,s=s+subst(QV[j+1],n,nn)*DN[nn-j+1]);s);S=vector(#R,i,(-1)^(r+i)*R[i]);deg=-1;DIF=S;for(m=1,30,DIF=vector(#DIF-1,i,DIF[i+1]-DIF[i]);my(z=1);for(i=1,#DIF,if(DIF[i]!=0,z=0;break));if(z,deg=m-1;break));W=polinterpolate(vector(deg+1,i,r+i),vector(deg+1,i,S[i]),n);for(i=1,#S,if(S[i]!=subst(W,n,r+i),ok=0));print(nm,": deg W=",deg,"  R_n=(-1)^n W(n) EXACT for all n=",r+1,"..900 : ",ok,"  content(W)=",factor(content(W)),"  t=",gettime());return(W);
read(concat(BASE,"rec_19_13.gp"));
W1=chk(PV,19,"(19,13) canonical");
read(concat(BASE,"rec_23_10.gp"));
W2=chk(PV,23,"(23,10) distinguished");
read(concat(BASE,"rec_19_13_constres.gp"));
W3=chk(PV,19,"(19,13) const-residual");
read(concat(BASE,"rec_17_15.gp"));
W4=chk(PV,17,"(17,15) distinguished");
print("W3 constant? ",poldegree(W3,n)<=0,"  digits ",#Str(abs(W3)),"  sign ",sign(W3));
write(concat(BASE,"resid_W.txt"),Str("W1913=",W1));
write(concat(BASE,"resid_W.txt"),Str("W2310=",W2));
write(concat(BASE,"resid_W.txt"),Str("Wconst=",W3));
write(concat(BASE,"resid_W.txt"),Str("W1715=",W4));
print("ALLDONE");
quit;
