default(parisize,"48G");
cn=read("cn.txt");
dn=read("dn900.txt");
read("rec_19_13.gp");
r=19;
NEW=3000;
P0=PV[1];
W=vector(10,i,my(nn=r+i); (-1)^nn*sum(j=0,r,subst(PV[j+1],n,nn)*dn[nn-j+1]));
m=8;
V=matrix(m,m,a,b,(r+a)^(b-1));
co=matsolve(V,vector(m,a,W[a])~);
WP=sum(k=1,m,co[k]*n^(k-1));
print("deg W = ",poldegree(WP));
C=vector(NEW+1);
DN=vector(NEW+1);
for(i=1,901,C[i]=cn[i]);
for(i=1,901,DN[i]=dn[i]);
step(nn)=my(p0=subst(P0,n,nn));my(s=sum(j=1,r,subst(PV[j+1],n,nn)*C[nn-j+1]));my(sd=sum(j=1,r,subst(PV[j+1],n,nn)*DN[nn-j+1]));C[nn+1]=-s/p0;DN[nn+1]=((-1)^nn*subst(WP,n,nn)-sd)/p0;0;
gettime();
for(nn=901,NEW,step(nn));
print("extension time ",gettime()," ms");
print("c_3000 integral? ",denominator(C[NEW+1])==1);
print("log10|c_3000| = ",log(abs(1.0*C[NEW+1]))/log(10));
print("sign c_3000 = ",sign(C[NEW+1]));
DD=vector(NEW+1);
DD[1]=1;
for(k=1,NEW,DD[k+1]=lcm(DD[k],k));
print("D_3000^7 d_3000 integral? ",denominator(DD[NEW+1]^7*DN[NEW+1])==1);
write("cn3000.txt",C);
write("dn3000.txt",DN);
print("written");
quit;
