default(parisize,"16G");
default(linewrap,0);
BASE="/tmp/claude-1000/-home-ubuntu-code-math-modular-sources/9a849c0a-95f8-4d19-b342-98033d0d9c03/scratchpad/zeta7/";
DN=read(concat(BASE,"dn900.txt"));
ND=900;
DL=vector(ND+1);
DL[1]=1;
for(m=1,ND,DL[m+1]=lcm(DL[m],m));
E=vector(ND+1,i,DL[i]^7*DN[i]);
ai=1;
for(i=1,ND+1,if(denominator(E[i])!=1,ai=0));
print("D_n^7 d_n integral for all n<=900: ",ai);
gettime();
Rat(QV,r,nn)=my(Ln=DL[nn+1],s=0);for(j=0,r,s=s+subst(QV[j+1],n,nn)*E[nn-j+1]*(Ln/DL[nn-j+1])^7);s/Ln^7;
chkf(QV,r,nm)=my(vals,S,W,deg=-1,DIF,bad=0);vals=vector(20,i,Rat(QV,r,r+i));S=vector(20,i,(-1)^(r+i)*vals[i]);DIF=S;for(m=1,19,DIF=vector(#DIF-1,i,DIF[i+1]-DIF[i]);my(z=1);for(i=1,#DIF,if(DIF[i]!=0,z=0;break));if(z,deg=m-1;break));W=polinterpolate(vector(deg+1,i,r+i),vector(deg+1,i,S[i]),n);for(nn=r+1,ND,if(Rat(QV,r,nn)!=(-1)^nn*subst(W,n,nn),bad=bad+1));print(nm,": deg W=",deg,"  content(W)=",factor(content(W)),"  R_n=(-1)^n W(n) failures over n=",r+1,"..900: ",bad,"  t=",gettime());return(W);
read(concat(BASE,"rec_19_13_constres.gp"));
Wc=chkf(PV,19,"(19,13) const-residual");
print("  W constant? ",poldegree(Wc,n)<=0,"   digits ",#Str(abs(Wc)));
CC=read(concat(BASE,"constres_C.txt"));
print("  agrees with C from the n<=400 run? ",Wc==C);
read(concat(BASE,"rec_17_15.gp"));
W17=chkf(PV,17,"(17,15) distinguished");
read(concat(BASE,"rec_19_13.gp"));
W19=chkf(PV,19,"(19,13) canonical recheck");
read(concat(BASE,"rec_23_10.gp"));
W23=chkf(PV,23,"(23,10) distinguished recheck");
write(concat(BASE,"resid_W.txt"),Str("Wconst=",Wc));
write(concat(BASE,"resid_W.txt"),Str("W1715=",W17));
write(concat(BASE,"resid_W.txt"),Str("W1913=",W19));
write(concat(BASE,"resid_W.txt"),Str("W2310=",W23));
print("ALLDONE");
quit;
