default(parisize,"16G");
default(linewrap,0);
BASE="/tmp/claude-1000/-home-ubuntu-code-math-modular-sources/9a849c0a-95f8-4d19-b342-98033d0d9c03/scratchpad/zeta7/";
DN=read(concat(BASE,"dn900.txt"));
ND=900;
DL=vector(ND+1);
DL[1]=1;
for(m=1,ND,DL[m+1]=lcm(DL[m],m));
E=vector(ND+1,i,DL[i]^7*DN[i]);
allint=1;
for(i=1,ND+1,if(denominator(E[i])!=1,allint=0));
print("D_n^7 d_n integral for all n<=900: ",allint);
gettime();
chkfast(QV,r,W,nm)=my(ok=1,bad=0);for(nn=r+1,ND,my(Ln=DL[nn+1],s=0);for(j=0,r,s=s+subst(QV[j+1],n,nn)*E[nn-j+1]*(Ln/DL[nn-j+1])^7);if(s!=(-1)^nn*subst(W,n,nn)*Ln^7,bad=bad+1));print(nm,": failures over n=",r+1,"..900 : ",bad,"   t=",gettime());
read(concat(BASE,"resid_W.txt"));
CC=read(concat(BASE,"constres_C.txt"));
read(concat(BASE,"rec_19_13_constres.gp"));
chkfast(PV,19,C+0*n,"(19,13) const-residual  R_n=(-1)^n*C");
read(concat(BASE,"rec_17_15.gp"));
print("done17? file resid_W may lack W1715");
quit;
