default(parisize,"24G");
default(linewrap,0);
BASE="/tmp/claude-1000/-home-ubuntu-code-math-modular-sources/9a849c0a-95f8-4d19-b342-98033d0d9c03/scratchpad/zeta7/";
DN=read(concat(BASE,"dn.txt"));
resid(PV,r,nmax)=vector(nmax-r,i,my(nn=r+i,s=0);for(j=0,r,s=s+subst(PV[j+1],n,nn)*DN[nn-j+1]);s);
ident(PV,r,nm)=my(R,S,deg,W,ok);R=resid(PV,r,400);S=vector(#R,i,(-1)^(r+i)*R[i]);deg=-1;my(DIF=S);for(m=1,30,DIF=vector(#DIF-1,i,DIF[i+1]-DIF[i]);my(z=1);for(i=1,#DIF,if(DIF[i]!=0,z=0;break));if(z,deg=m-1;break));print("== ",nm," ==  (-1)^n R_n is polynomial of degree ",deg);W=polinterpolate(vector(deg+1,i,r+i),vector(deg+1,i,S[i]),n);ok=1;for(i=1,#S,if(S[i]!=subst(W,n,r+i),ok=0));print("  EXACT check R_n = (-1)^n W(n) for all n=",r+1,"..400: ",ok);print("  content of W = ",content(W),"  factored: ",factor(content(W)));print("  W/content factored over Q: ",factor(W/content(W)));print("  W = ",W);return([R,W]);
read(concat(BASE,"rec_19_13.gp"));
A=ident(PV,19,"(19,13) canonical");
P0=PV[1];
P19=PV[20];
Q0=P0/n^7;
Q19=P19/(n-18)^7;
W=A[2];
print("  W / Q0 as rational? ",W/Q0);
print("  W / Q19 = ",W/Q19);
print("  W / subst(Q0,n,n-1) = ",W/subst(Q0,n,n-1));
read(concat(BASE,"rec_23_10.gp"));
B=ident(PV,23,"(23,10) distinguished");
quit;
