default(parisize,"48G");
cn=read("cn.txt");
dn=read("dn900.txt");
read("rec_19_13.gp");
r=19;
print("#PV = ",#PV,"  degrees: ",vector(#PV,i,poldegree(PV[i])));
bad=0;
for(nn=r+1,900, my(s=sum(j=0,r,subst(PV[j+1],n,nn)*cn[nn-j+1])); if(s!=0, bad++));
print("c-annihilation failures n=20..900 : ",bad);
W=vector(20,i,my(nn=r+i); (-1)^nn*sum(j=0,r,subst(PV[j+1],n,nn)*dn[nn-j+1]));
m=8;
V=matrix(m,m,a,b,(r+a)^(b-1));
co=matsolve(V,vector(m,a,W[a])~);
P=sum(k=1,m,co[k]*n^(k-1));
print("fitted W(n) = ",P);
bad2=0;
for(nn=r+1,900, my(s=sum(j=0,r,subst(PV[j+1],n,nn)*dn[nn-j+1])); if(s!=(-1)^nn*subst(P,n,nn), bad2++));
print("R_n = (-1)^n W(n) failures n=20..900 : ",bad2,"   deg W = ",poldegree(P),"   content = ",factor(content(P)));
print("W(n)/content = ",P/content(P));
quit;
