default(parisize,"48G");
C=read("cn3000.txt");
DN=read("dn3000.txt");
read("rec_19_13.gp");
read("rec_prime_18_13.gp");
NN=3000;
r=19;rp=18;
cp=vector(NN,i,C[i+1]+C[i]);
dp=vector(NN,i,DN[i+1]+DN[i]);
W=vector(10,i,my(nn=r+i);(-1)^nn*sum(j=0,r,subst(PV[j+1],n,nn)*DN[nn-j+1]));
m=8;V=matrix(m,m,a,b,(r+a)^(b-1));co=matsolve(V,vector(m,a,W[a])~);
WP=sum(k=1,m,co[k]*n^(k-1));
print("W(n) content = ",factor(content(WP)),"  deg = ",poldegree(WP));
bad=0;
for(nn=rp+1,NN,my(s=sum(j=0,rp,subst(PVP[j+1],n,nn)*cp[nn-j]));if(s!=0,bad++));
print("primed 19-term recurrence: c'-annihilation failures n=19..3000 : ",bad);
bad2=0;
for(nn=rp+1,NN,my(s=sum(j=0,rp,subst(PVP[j+1],n,nn)*dp[nn-j]));if(s!=(-1)^nn*subst(WP,n,nn),bad2++));
print("primed: R'_n = (-1)^n W(n) (SAME W) failures n=19..3000 : ",bad2);
bad3=0;
for(nn=r+1,NN,my(s=sum(j=0,r,subst(PV[j+1],n,nn)*C[nn-j+1]));if(s!=0,bad3++));
print("unprimed (19,13): c-annihilation failures n=20..3000 : ",bad3);
bad4=0;
for(nn=r+1,NN,my(s=sum(j=0,r,subst(PV[j+1],n,nn)*DN[nn-j+1]));if(s!=(-1)^nn*subst(WP,n,nn),bad4++));
print("unprimed: R_n = (-1)^n W(n) failures n=20..3000 : ",bad4);
print("chi of primed recurrence: ",factor(sum(j=0,rp,polcoeff(PVP[j+1],13)*L^(rp-j))));
print("P'_0 = n^7 * ? : valuation ",valuation(PVP[1],n));
print("P'_18 valuation at n=17: ",valuation(subst(PVP[rp+1],n,n+17),n));
quit;
