/* 12_polylog.gp -- weight-two polylogarithm battery for the five-point periods.
 * For a row with characteristic roots lambda_i the singular points are t=1/lambda_i;
 * the natural weight-two constants are zeta(2), log(a)log(b) and Li_2(z) for z in the
 * multiplicative group generated by the ratios lambda_i/lambda_j and 1 - lambda_i/lambda_j.
 */
default(realprecision, 90);

dilog2(zz) = if(zz == 0, 0.0, -intnum(tt = 0, 1, log(1 - zz*tt)/tt));

/* greedy independent subset: keep only constants not already in the span */
indep(vv, tol) =
{ my(bas = List(), nm = List());
  for(i = 1, #vv,
    my(cand = concat(Vec(bas), [vv[i]]), rel);
    rel = if(#cand == 1, 0, lindep(cand));
    if(rel == 0 || vecmax(apply(abs, rel)) > 10^7
       || abs(sum(k = 1, #cand, rel[k]*cand[k])) > 10.0^(-tol)*vecmax(apply(abs, rel)),
       listput(bas, vv[i]); listput(nm, i)));
  [Vec(bas), Vec(nm)];
}

wtest(lab, xv, gens, extraz) =
{ my(nm = List(), vv = List(), rel, hh, ii, bas);
  listput(nm, "zeta(2)"); listput(vv, zeta(2));
  listput(nm, "1"); listput(vv, 1.0);
  for(i = 1, #gens, for(j = i, #gens,
      listput(nm, Str("log(", gens[i], ")log(", gens[j], ")"));
      listput(vv, log(abs(gens[i]))*log(abs(gens[j])))));
  for(i = 1, #extraz,
      listput(nm, Str("Li2(", extraz[i], ")")); listput(vv, dilog2(extraz[i])));
  ii = indep(Vec(vv), 50);
  bas = concat([xv], ii[1]);
  rel = lindep(bas);
  if(rel == 0, print(lab, "  no relation"); return(0));
  hh = vecmax(apply(abs, rel));
  if(rel[1] == 0 || hh > 10^6, print(lab, "  UNIDENTIFIED (dim ", #bas, ", h=", hh, ")"); return(0));
  if(abs(sum(i = 1, #bas, rel[i]*bas[i])) > 10.0^(-48)*hh,
     print(lab, "  UNIDENTIFIED (dim ", #bas, ", residual)"); return(0));
  print(lab, "  xi: ", rel, "  basis idx ", ii[2], " of ", Vec(nm));
  1;
}
