default(parisize,"14G");
default(realprecision,220);
M = 900;
et(k)=prod(m=1,M\k+1,1-'q^(k*m)+O('q^(M+2)));
D(s)='q*deriv(s,'q);
ev(s,z)=subst(truncate(s),'q,z);
E8(k)=1+480*sum(m=1,M\k+1,sigma(m,7)*'q^(k*m))+O('q^(M+2));
X = 'q*et(4)^2*et(12)^2/(et(1)^2*et(3)^2);
T = X/(16*X^2+2*X+1);
PH = (E8(1)-572*E8(2)+11583*E8(3)-36608*E8(4)+46332*E8(6)-20736*E8(12))/480;
F = PH/D(T);
print("=== level-12 zeta(7) parent,  N=12, weight(F)=6, B=2, C=16");
print("x = ", X+O('q^8));
print("t = ", T+O('q^9));
print("Phi_12^- = ", PH+O('q^9));
print("F = ", F+O('q^8));
NA=1300;
QT = serreverse(T+O('q^(NA+1)));
AT = subst(F+O('q^(NA+1)),'q,QT);
print("A_0..A_8 = ", vector(9,j,polcoef(AT,j-1)));
print("A_n integral for n<=", NA, ": ", denominator(content(truncate(AT)))==1);
S = F/D(X)^3;
print("x^3*S = F/(Dx/x)^3 = ", X^3*S+O('q^8));
rf(GG,U,d1,d2,NC)={
  my(cols=List(), Ms);
  for(j=0,d1, listput(cols, Vec(truncate(U^j+O('q^(NC+1))),-(NC+1))));
  for(j=0,d2, listput(cols, Vec(truncate(-GG*U^j+O('q^(NC+1))),-(NC+1))));
  Ms = Mat(vector(#cols,i,cols[i]~));
  matker(Ms);
}
{for(d=0,8, my(k=rf(X^3*S,X,d,d,4*d+60)); if(#k>0, print("  x^3 S rational in x, degree ",d,": ",k~); break));}
qc = exp(-Pi/sqrt(3));
tp = 1/10; xc = 1/4;
print("q_c = ", qc);
print("x(q_c) - 1/4  = ", ev(X,qc)-xc);
print("t(q_c) - 1/10 = ", ev(T,qc)-tp);
print("Dt(q_c)       = ", ev(D(T),qc));
Fv=ev(F,qc); DFv=ev(D(F),qc); D2T=ev(D(D(T)),qc); Dx=ev(D(X),qc);
print("F(tau_c)      = ", Fv);
print("DF(tau_c)     = ", DFv);
print("DF - (6 sqrt12/(4Pi))F = ", DFv - 6*sqrt(12)/(4*Pi)*Fv);
print("D2t(tau_c)    = ", D2T);
Kf = sqrt(tp*DFv^2/(2*Pi*(-D2T)));
print("K (fold)      = ", Kf);
th=1.9; N=12; tau=(cos(th)+I*sin(th))/sqrt(N); taup=-1/(N*tau);
q1=exp(2*Pi*I*tau); q2=exp(2*Pi*I*taup);
print("Phi|_8 W_12 / Phi = ", ev(PH,q2)/((sqrt(N)*tau)^8*ev(PH,q1)));
print("F|_6 W_12 / F     = ", ev(F,q2)/((sqrt(N)*tau)^6*ev(F,q1)));
print("x(Wtau)*x(tau)    = ", ev(X,q2)*ev(X,q1), "  1/C=",1/16.);
MPTS=18; H=50; N0=NA;
Kn(m)=abs(polcoef(AT,m))*tp^m*m^(3/2);
ns=vector(MPTS,j,N0-H*(j-1));
sol=matsolve(matrix(MPTS,MPTS,r,s,1/ns[r]^(s-1)),vector(MPTS,r,Kn(ns[r]))~);
sol2=matsolve(matrix(MPTS-2,MPTS-2,r,s,1/ns[r]^(s-1)),vector(MPTS-2,r,Kn(ns[r]))~);
print("K (Richardson ",MPTS,") = ", sol[1]);
print("K (Richardson ",MPTS-2,") = ", sol2[1]);
print("K fold/K Rich - 1 = ", Kf/sol[1]-1);
print("signs A_n near NA: ", vector(6,j,sign(polcoef(AT,NA-j+1))));
W2 = gamma(1/3)^6/Pi^4;
print("Dx(tau_c)     = ", Dx);
print("Dx/W2 = ", Dx/W2, "  algdep 2: ", algdep(Dx/W2,2), "  algdep 4: ", algdep(Dx/W2,4), " algdep 6: ", algdep(Dx/W2,6));
print("(Dx/W2)^3 algdep 2: ", algdep((Dx/W2)^3,2));
print("K*Pi^(3/2)/W2^2 = ", Kf*Pi^(3/2)/W2^2);
print("  algdep 2: ", algdep(Kf*Pi^(3/2)/W2^2,2));
print("  algdep 4: ", algdep(Kf*Pi^(3/2)/W2^2,4));
print("  algdep 6: ", algdep(Kf*Pi^(3/2)/W2^2,6));
print("  ^3 algdep 2: ", algdep((Kf*Pi^(3/2)/W2^2)^3,2));
print("  ^6 algdep 2: ", algdep((Kf*Pi^(3/2)/W2^2)^6,2));
print("K*Pi^(19/2)/Gamma(1/3)^12 = ", Kf*Pi^(19/2)/gamma(1/3)^12);
quit;
