/* 01_hosts.gp -- genus-0 Atkin-Lehner quotients X_0(N)/W_S with 4 | N.
   genus(X_0(N)/W_S) = dim of the joint (+1)-eigenspace of {W_Q : Q in S} on
   S_2(Gamma_0(N)).   Also record, for each W_Q, its square on M_k(N,chi_{-4}):
      W_Q^2 = chi_Q(-1) * chi_{N/Q}(Q)  (Atkin-Li)
   which for chi = chi_{-4} is  -1 if 4|Q,  chi_{-4}(Q) if Q odd.
*/
default(parisizemax, 4000000000);
ncusp0(n) = sumdiv(n, d, eulerphi(gcd(d,n/d)));

{alsq(n,q) = /* W_Q^2 on M_k(Gamma_0(n),chi_{-4}) : +1 or -1 */
  if(q%4==0, -1, if(q%4==1, 1, -1));}

{hosts(n) =
  my(mf = mfinit([n,2],1), d = mfdim(mf));
  my(prim = select(q->(q>1 && gcd(q,n/q)==1), divisors(n)));
  /* AL group generated by prime-power exact divisors */
  my(gens = select(q->(isprimepower(q) && gcd(q,n/q)==1), divisors(n)));
  my(mats = vector(#gens, i, if(d>0, my(al=mfatkininit(mf,gens[i])); al[2]/al[3], matrix(0,0))));
  my(res = List());
  /* enumerate subgroups = all subsets of gens (AL group is (Z/2)^r) */
  for(mask=0, 2^#gens-1,
    my(sel = select(i->bittest(mask,i-1), vector(#gens,i,i)));
    my(g);
    if(d==0, g=0,
      my(P = matid(d));
      for(j=1,#sel, P = P*(matid(d)+mats[sel[j]])/2);
      g = matrank(P);
    );
    if(g==0,
      my(qs = vector(#sel,j,gens[sel[j]]));
      listput(res, [qs, mask]);
    );
  );
  res;
}

print("N | genus0 AL subgroups (generators) | ncusps(N)");
{for(n=4,120, if(n%4==0,
  my(h = hosts(n));
  if(#h>0,
    print1(n, " : ");
    for(i=1,#h, print1(if(#h[i][1]==0,"{}",Str(h[i][1])), " "));
    print("   ncusp0=", ncusp0(n));
  );
));}
quit;
