default(parisizemax,4000000000);
N = 46;
rowR2(a,b,c,n)={my(A=vector(n+1),B=vector(n+1));A[1]=1;A[2]=b;B[1]=0;B[2]=1;
  for(k=1,n-1, A[k+2]=((a*k^2+a*k+b)*A[k+1]-c*k^2*A[k])/(k+1)^2;
               B[k+2]=((a*k^2+a*k+b)*B[k+1]-c*k^2*B[k])/(k+1)^2);[A,B]};
R = rowR2(12,4,32,N); AE = R[1]; BE = R[2];
chi(n) = if(n%2==0,0, if(n%4==1,1,-1));
Ecoef = vector(N, m, sumdiv(m, d, chi(m/d)*d^2));
V2(v) = vector(#v, m, if(m%2==0, v[m/2], 0));
lc(v,w,al,be) = vector(#v, m, al*v[m]+be*w[m]);
E1=Ecoef; E2=V2(Ecoef);
PhiE=lc(E1,E2,1,-8); Phi0=lc(E1,E2,1,-4); PhiH=lc(E1,E2,1,-2);
Aser = sum(n=0,N-1, AE[n+1]*x^n) + O(x^N);
Gser = intformal(Aser);
D1PhiE = sum(m=1,N-1, PhiE[m]/m*q^m) + O(q^N);
tq = subst(serreverse(Gser),x,D1PhiE);
Fq = subst(Aser,x,tq);
qinv = serreverse(tq);
Bof(Psi) = subst(Fq*(sum(m=1,N-1,Psi[m]/m^2*q^m)+O(q^N)), q, qinv);
BEt=Bof(PhiE); B0t=Bof(Phi0); BHt=Bof(PhiH); B1t=Bof(E1);
print("check B_PhiE == census b_n : ", vector(8,j, polcoeff(BEt,j)==BE[j+1]));
print("t(q)=",tq+O(q^6)); print("F(q)=",Fq+O(q^6));
print("\n n : v2(B0_n)  v2/n   |  v2(BE_n - xi2*a_n) needs xi2; ratio B0_n/a_n");
G = Catalan;
for(n=1,N-1, my(c0=polcoeff(B0t,n)); print1("n=",n," v2=",valuation(c0,2)," r=",valuation(c0,2)*1./n));
print("\narchimedean limits (b_n/a_n):");
for(j=1,4, my(n=[10,20,30,40][j]); print("  n=",n,"  B_E: ",polcoeff(BEt,n)/AE[n+1]*1.," (G/2=",G/2,")   B_0: ",polcoeff(B0t,n)/AE[n+1]*1.,"   B_H: ",polcoeff(BHt,n)/AE[n+1]*1.," (G/4=",G/4,")"));
print("\ndenominators: is d_n^k * coeff integral?");
dn(n)=lcm(vector(n,j,j));
for(k=1,3, my(okE=1,ok0=1); for(n=1,N-1, if(denominator(dn(n)^k*polcoeff(BEt,n))!=1,okE=0); if(denominator(dn(n)^k*polcoeff(B0t,n))!=1,ok0=0)); print("  k=",k,": d_n^k B_E integral? ",okE,"   d_n^k B_0 integral? ",ok0));
