\\ 3-adic Apery limits and rigidity checks for Zagier rows B, C, F
N=400;
rows(a,b,c)={my(A=vector(N+1),B=vector(N+1));A[1]=1;A[2]=b;B[1]=0;B[2]=1;
 for(n=1,N-1,A[n+2]=((a*n^2+a*n+b)*A[n+1]-c*n^2*A[n])/(n+1)^2;
            B[n+2]=((a*n^2+a*n+b)*B[n+1]-c*n^2*B[n])/(n+1)^2);[A,B]};
RB=rows(9,3,27); RC=rows(10,3,9); RF=rows(17,6,72);
RR=[RB,RC,RF]; NM=["B","C","F"];
for(j=1,3, my(R,c0,mx); R=RR[j];
  c0=sum(n=0,N, valuation(R[1][n+1],3)==0);
  mx=vecmax(vector(N+1,i,valuation(R[1][i],3)));
  print(NM[j],": #{n<=",N,": v3(a_n)=0} = ",c0,"   max_n v3(a_n) = ",mx));
xC=RC[2][N+1]/RC[1][N+1]; xF=RF[2][N+1]/RF[1][N+1]; xB=RB[2][N+1]/RB[1][N+1];
print();
print("v3(xi) = ",valuation(xC,3)," (all three)");
p3(z,k)=my(v=valuation(z,3));Str("3^",v," * ",lift(Mod(numerator(z/3^v),3^k)*Mod(denominator(z/3^v),3^k)^-1));
print("xi_C      = ", p3(xC,40));
print("(5/4)xi_C = ", p3(5*xC/4,40));
print("xi_F      = ", p3(xF,40));
print("xi_B      = ", p3(xB,40));
print();
print("v3(4 xi_F - 5 xi_C) = ",valuation(4*xF-5*xC,3),"   [expected ~ 2N = ",2*N,"]");
print("v3(xi_B - xi_C)     = ",valuation(xB-xC,3));
