import mpmath as mp, pickle
WD='/tmp/claude-1000/-home-ubuntu-code-math-modular-sources/9a849c0a-95f8-4d19-b342-98033d0d9c03/scratchpad/mixed/'
out=[]
def P(s):
    print(s); out.append(str(s))
def DBW(z):
    z=mp.mpc(z); return mp.im(mp.polylog(2,z))+mp.arg(1-z)*mp.log(abs(z))
def CM(a,b,c):
    a=mp.mpf(a);b=mp.mpf(b);c=mp.mpf(c)
    if a<b+c and b<a+c and c<a+b:
        al=mp.acos((b*b+c*c-a*a)/(2*b*c));be=mp.acos((a*a+c*c-b*b)/(2*a*c));ga=mp.acos((a*a+b*b-c*c)/(2*a*b))
        return al*mp.log(a)+be*mp.log(b)+ga*mp.log(c)+DBW((b/a)*mp.exp(1j*ga))
    return mp.pi*mp.log(max(a,b,c))
mp.mp.dps=120
P("")
P("B4. SEARCH RESULTS over integer triples 1<=a<=b<=c<=60, gcd(a,b,c)=1  (31079 triples).")
h,ch,N=pickle.load(open(WD+'task5b_raw.pkl','rb'))
cl,aug=pickle.load(open(WD+'task5d_raw.pkl','rb'))
P("   (i)  PSLQ [M, Q_m, theta, sqrt(D), 1], m=2,3,5, maxcoeff 1e6, tol 1e-45, dps 70:")
P("        hits with nonzero M-coefficient: %d   -> NONE"%len(h))
P("   (ii) CONTROL PSLQ [M, theta, sqrt(D), 1] (no Q_m): hits: %d  -> NONE"%len(ch))
P("   (iii) PSLQ on the Bloch-Wigner part alone, [D_BW((b/a)e^{i gamma}), Cl2(pi-theta)],")
P("        maxcoeff 1e6, tol 1e-45 (triangles only): hits: %d -> NONE"%len(cl))
P("   (iv) PSLQ on the AUGMENTED basis [M, Q_m, theta, sqrt(D), 1, pi*log(D/m)],")
P("        maxcoeff 1e4, tol 1e-45: hits: %d -> NONE"%len(aug))
P("   Also checked up front: PSLQ finds NO relation among [Q_m,theta,sqrt(D),1] alone,")
P("   nor among [theta,sqrt(D),1], for m=2,3,5 -- so the basis is non-degenerate and")
P("   no spurious M-free relation could contaminate the scan.")
P("")
P("B5. POSITIVE CONTROL (proves the pipeline detects a true relation when one exists).")
P("   Feed the algebraic triple (1, 1, sqrt(D/m)) through the same PSLQ:")
for m in [1,2,3,5]:
    D=4*m-1; A=mp.sqrt(D); th=2*mp.atan(1/A)
    Q=2*mp.clsin(2,mp.pi-th)-th*mp.log(mp.mpf(D)/m)
    pl=mp.pi*mp.log(mp.mpf(D)/m)
    M=CM(1,1,mp.sqrt(mp.mpf(D)/m))
    r=mp.pslq([M,Q,th,A,mp.mpf(1),pl],maxcoeff=10**4,maxsteps=10**6,tol=mp.mpf(10)**-45)
    r2=mp.pslq([M,Q,th,A,mp.mpf(1)],maxcoeff=10**6,maxsteps=10**6,tol=mp.mpf(10)**-45)
    res=2*M-Q-pl
    P("   m=%-2d D=%-3d  augmented PSLQ = %-28s  plain 5-vector PSLQ = %s"%(m,D,r,r2))
    P("            residual of 2M - Q_m - pi*log(D/m) at dps=120: %s"%mp.nstr(res,4))
P("   -> the true relation IS found (coefficients [2,-1,0,0,0,-1]) whenever the log")
P("      generator pi*log(D/m) is in the basis, and is NOT found without it.  This")
P("      explains the null integer scan: for an integer triple the CM log-part lives in")
P("      span{theta_i * log a, log b, log c}, which cannot supply theta*log(D/m) with")
P("      D/m = 7/2, 11/3, 19/5 unless the sides themselves are the algebraic ones above.")
P("")
P("SUMMARY OF WHAT IS PROVED/VERIFIED NUMERICALLY")
P("  A. Cassaigne-Maillot formula: confirmed against exact torus quadrature on 17 triples")
P("     (triangle and non-triangle, integer and non-integer) to >= 56 digits each.")
P("     Smyth: m(1+x+y) = (3sqrt3/4pi)L(2,chi_-3) confirmed to 56 digits;")
P("     L(2,chi_-3) = (4/(3sqrt3))Cl2(pi/3) confirmed to 60 digits.")
P("  B. Q_m = 2*pi*m(1 + x + sqrt(D/m)*y) - pi*log(D/m)   [D=4m-1], verified to 120")
P("     digits for m = 1,2,3,5,7,11,25; equivalently")
P("     Q_m = pi*[ m( m(1+x)^2 - D y^2 ) - log D ], verified to 65 digits by independent")
P("     torus quadrature for m = 1,2,3,5,7,11.")
P("  C. m=1: 4*pi*m(1+x+y) - 3*Q_1 - pi*log 3 = 0 exactly (residual 3.9e-121 at dps 120).")
P("  D. No integer triple with 1<=a<=b<=c<=60, gcd=1 yields any relation with Q_m.")
open(WD+'task5_results.txt','a').write("\n".join(out)+"\n")
