default(parisizemax, 8000000000);
default(realprecision, 60);
NQ = 140;
NA = 108;
NB = 420;
useries(dv, r, nq) = q*prod(t=1, #dv, eta(q^dv[t] + O(q^nq))^r[t]);
Fseries(dv, r, nq) = 1 - sum(t=1, #dv, r[t]*dv[t]*sum(n=1, (nq-1)\dv[t], sigma(n)*q^(dv[t]*n))) + O(q^nq);
peel2(Fs, xs, na, nq) = my(a=vector(na+1), G=Fs, xp=1+O(q^nq)); for(n=0, na, my(c=polcoeff(G,n)); a[n+1]=c; if(c!=0, G=G-c*xp); xp=xp*xs); a;
fitrec(av, dg) = my(nv=3*(dg+1), rows=List()); for(n=0, #av-4, my(row=vector(nv)); for(j=0,2, for(e=0,dg, row[j*(dg+1)+e+1] = n^e*av[n+j+1])); listput(rows,row)); matker(matconcat(Vec(rows)~));
polsof(kv, dg) = vector(3, j, sum(e=0, dg, kv[(j-1)*(dg+1)+e+1]*x^e));
normP(P) = my(g=content(concat(concat(Vec(P[1]),Vec(P[2])),Vec(P[3])))); vector(3,j,P[j]/g);
freetest(a, nn) = my(f=1); for(n=1, nn, if(a[n+1] % (n+1) != 0, f=0; break)); f;
denexp(bb, nn) = my(dn=1, km=0); for(n=1, nn, dn=lcm(dn,n); my(bn=bb[n+1]); if(bn!=0, my(de=denominator(bn), kj=0, t=de); while(t>1 && kj<12, kj++; t=t/gcd(t,dn)); if(kj>km, km=kj))); km;
iterrec(P, a0, a1, nb) = my(v=vector(nb+3)); v[1]=a0; v[2]=a1; for(n=0, nb, my(p0=subst(P[1],x,n), p1=subst(P[2],x,n), p2=subst(P[3],x,n)); if(p2==0, break); v[n+3] = -(p0*v[n+1]+p1*v[n+2])/p2); v;
dv=[1,2,3,6]; r=[-5,1,-1,5]; C=72; B=17;
us = useries(dv,r,NQ); Fs = Fseries(dv,r,NQ); xs = us/(1+B*us+C*us^2);
a = peel2(Fs, xs, NA, NQ);
print("a[1..8] = ", vector(8,i,a[i]));
ker = fitrec(a, 3); print("recdim = ", matsize(ker)[2]);
P = normP(polsof(ker[,1], 3));
print("P0=",P[1]); print("P1=",P[2]); print("P2=",P[3]);
print("charpoly = ", sum(j=1,3, polcoeff(P[j],3)*y^(j-1)));
print("free int = ", freetest(a, 60));
aa = iterrec(P, a[1], a[2], NB);
print("recurrence reproduces a: ", vector(20,i,aa[i]==a[i]));
bb = iterrec(P, 0, 1, NB);
print("k = ", denexp(bb, 140));
print("xi ~ ", bb[NB+1]*1.0/aa[NB+1]);
print("zeta(3)/6 = ", zeta(3)/6);
quit;
