default(parisizemax, 12000000000);
default(realprecision, 260);
NQ = 150; NA = 118; NB = 330;
useries(dv, r, nq) = q*prod(t=1, #dv, eta(q^dv[t] + O(q^nq))^r[t]);
Fseries(dv, r, nq) = 1 - sum(t=1, #dv, r[t]*dv[t]*sum(n=1, (nq-1)\dv[t], sigma(n)*q^(dv[t]*n))) + O(q^nq);
peel2(Fs, xs, na, nq) = my(a=vector(na+1), G=Fs, xp=1+O(q^nq)); for(n=0, na, my(c=polcoeff(G,n)); a[n+1]=c; if(c!=0, G=G-c*xp); xp=xp*xs); a;
fitrecR(av, ord, dg) = my(nv=(ord+1)*(dg+1), rows=List()); for(n=0, #av-ord-2, my(row=vector(nv)); for(j=0,ord, for(e=0,dg, row[j*(dg+1)+e+1] = n^e*av[n+j+1])); listput(rows,row)); matker(matconcat(Vec(rows)~));
normPR(P) = my(v=[]); for(j=1,#P, v=concat(v,Vec(P[j]))); my(g=content(v)); vector(#P,j,P[j]/g);
freetest(a, nn) = my(f=1); for(n=1, nn, if(a[n+1] % (n+1) != 0, f=0; break)); f;
denexp(bb, nn) = my(dn=1, km=0); for(n=1, nn, dn=lcm(dn,n); my(bn=bb[n+1]); if(bn!=0, my(de=denominator(bn), kj=0, t=de); while(t>1 && kj<12, kj++; t=t/gcd(t,dn)); if(kj>km, km=kj))); km;
iterrec2(P, a0, a1, nb) = my(v=vector(nb+3)); v[1]=a0; v[2]=a1; for(n=0, nb, my(p0=subst(P[1],x,n), p1=subst(P[2],x,n), p2=subst(P[3],x,n)); if(p2==0, break); v[n+3] = -(p0*v[n+1]+p1*v[n+2])/p2); v;

print("### N=",5," C=",125," B=",22," deg=",1," r=",[-6, 6]);
dv=[1, 5]; r=[-6, 6]; C=125; B=22;
us=useries(dv,r,NQ); Fs=Fseries(dv,r,NQ); xs=us/(1+B*us+C*us^2);
a=peel2(Fs,xs,NA,NQ);
print("a = ", vector(10,i,a[i]));
ker=fitrecR(a,2,3); P=normPR(vector(3,j,sum(e=0,3,ker[(j-1)*4+e+1,1]*x^e)));
print("P0 = ", P[1]); print("P1 = ", P[2]); print("P2 = ", P[3]);
print("charpoly = ", sum(j=1,3, polcoeff(P[j],3)*y^(j-1)));
print("freeint = ", freetest(a,70));
aa=iterrec2(P,a[1],a[2],NB); bb=iterrec2(P,0,1,NB);
rep=1; for(i=1,min(#a,50), if(aa[i]!=a[i], rep=0; break)); print("reproduces = ", rep);
print("k = ", denexp(bb,150));
xi = bb[NB]*1.0/aa[NB]; print("xi  = ", xi);
print("xi' = ", bb[NB-1]*1.0/aa[NB-1]);

print("### N=",6," C=",81," B=",14," deg=",2," r=",[-4, -4, 4, 4]);
dv=[1, 2, 3, 6]; r=[-4, -4, 4, 4]; C=81; B=14;
us=useries(dv,r,NQ); Fs=Fseries(dv,r,NQ); xs=us/(1+B*us+C*us^2);
a=peel2(Fs,xs,NA,NQ);
print("a = ", vector(10,i,a[i]));
ker=fitrecR(a,2,3); P=normPR(vector(3,j,sum(e=0,3,ker[(j-1)*4+e+1,1]*x^e)));
print("P0 = ", P[1]); print("P1 = ", P[2]); print("P2 = ", P[3]);
print("charpoly = ", sum(j=1,3, polcoeff(P[j],3)*y^(j-1)));
print("freeint = ", freetest(a,70));
aa=iterrec2(P,a[1],a[2],NB); bb=iterrec2(P,0,1,NB);
rep=1; for(i=1,min(#a,50), if(aa[i]!=a[i], rep=0; break)); print("reproduces = ", rep);
print("k = ", denexp(bb,150));
xi = bb[NB]*1.0/aa[NB]; print("xi  = ", xi);
print("xi' = ", bb[NB-1]*1.0/aa[NB-1]);

print("### N=",6," C=",72," B=",17," deg=",1," r=",[-5, 1, -1, 5]);
dv=[1, 2, 3, 6]; r=[-5, 1, -1, 5]; C=72; B=17;
us=useries(dv,r,NQ); Fs=Fseries(dv,r,NQ); xs=us/(1+B*us+C*us^2);
a=peel2(Fs,xs,NA,NQ);
print("a = ", vector(10,i,a[i]));
ker=fitrecR(a,2,3); P=normPR(vector(3,j,sum(e=0,3,ker[(j-1)*4+e+1,1]*x^e)));
print("P0 = ", P[1]); print("P1 = ", P[2]); print("P2 = ", P[3]);
print("charpoly = ", sum(j=1,3, polcoeff(P[j],3)*y^(j-1)));
print("freeint = ", freetest(a,70));
aa=iterrec2(P,a[1],a[2],NB); bb=iterrec2(P,0,1,NB);
rep=1; for(i=1,min(#a,50), if(aa[i]!=a[i], rep=0; break)); print("reproduces = ", rep);
print("k = ", denexp(bb,150));
xi = bb[NB]*1.0/aa[NB]; print("xi  = ", xi);
print("xi' = ", bb[NB-1]*1.0/aa[NB-1]);

print("### N=",6," C=",64," B=",20," deg=",2," r=",[-6, 6, -6, 6]);
dv=[1, 2, 3, 6]; r=[-6, 6, -6, 6]; C=64; B=20;
us=useries(dv,r,NQ); Fs=Fseries(dv,r,NQ); xs=us/(1+B*us+C*us^2);
a=peel2(Fs,xs,NA,NQ);
print("a = ", vector(10,i,a[i]));
ker=fitrecR(a,2,3); P=normPR(vector(3,j,sum(e=0,3,ker[(j-1)*4+e+1,1]*x^e)));
print("P0 = ", P[1]); print("P1 = ", P[2]); print("P2 = ", P[3]);
print("charpoly = ", sum(j=1,3, polcoeff(P[j],3)*y^(j-1)));
print("freeint = ", freetest(a,70));
aa=iterrec2(P,a[1],a[2],NB); bb=iterrec2(P,0,1,NB);
rep=1; for(i=1,min(#a,50), if(aa[i]!=a[i], rep=0; break)); print("reproduces = ", rep);
print("k = ", denexp(bb,150));
xi = bb[NB]*1.0/aa[NB]; print("xi  = ", xi);
print("xi' = ", bb[NB-1]*1.0/aa[NB-1]);

print("### N=",7," C=",49," B=",13," deg=",1," r=",[-4, 4]);
dv=[1, 7]; r=[-4, 4]; C=49; B=13;
us=useries(dv,r,NQ); Fs=Fseries(dv,r,NQ); xs=us/(1+B*us+C*us^2);
a=peel2(Fs,xs,NA,NQ);
print("a = ", vector(10,i,a[i]));
ker=fitrecR(a,2,3); P=normPR(vector(3,j,sum(e=0,3,ker[(j-1)*4+e+1,1]*x^e)));
print("P0 = ", P[1]); print("P1 = ", P[2]); print("P2 = ", P[3]);
print("charpoly = ", sum(j=1,3, polcoeff(P[j],3)*y^(j-1)));
print("freeint = ", freetest(a,70));
aa=iterrec2(P,a[1],a[2],NB); bb=iterrec2(P,0,1,NB);
rep=1; for(i=1,min(#a,50), if(aa[i]!=a[i], rep=0; break)); print("reproduces = ", rep);
print("k = ", denexp(bb,150));
xi = bb[NB]*1.0/aa[NB]; print("xi  = ", xi);
print("xi' = ", bb[NB-1]*1.0/aa[NB-1]);

print("### N=",8," C=",32," B=",12," deg=",1," r=",[-4, 2, -2, 4]);
dv=[1, 2, 4, 8]; r=[-4, 2, -2, 4]; C=32; B=12;
us=useries(dv,r,NQ); Fs=Fseries(dv,r,NQ); xs=us/(1+B*us+C*us^2);
a=peel2(Fs,xs,NA,NQ);
print("a = ", vector(10,i,a[i]));
ker=fitrecR(a,2,3); P=normPR(vector(3,j,sum(e=0,3,ker[(j-1)*4+e+1,1]*x^e)));
print("P0 = ", P[1]); print("P1 = ", P[2]); print("P2 = ", P[3]);
print("charpoly = ", sum(j=1,3, polcoeff(P[j],3)*y^(j-1)));
print("freeint = ", freetest(a,70));
aa=iterrec2(P,a[1],a[2],NB); bb=iterrec2(P,0,1,NB);
rep=1; for(i=1,min(#a,50), if(aa[i]!=a[i], rep=0; break)); print("reproduces = ", rep);
print("k = ", denexp(bb,150));
xi = bb[NB]*1.0/aa[NB]; print("xi  = ", xi);
print("xi' = ", bb[NB-1]*1.0/aa[NB-1]);

print("### N=",8," C=",16," B=",24," deg=",2," r=",[-8, 16, -16, 8]);
dv=[1, 2, 4, 8]; r=[-8, 16, -16, 8]; C=16; B=24;
us=useries(dv,r,NQ); Fs=Fseries(dv,r,NQ); xs=us/(1+B*us+C*us^2);
a=peel2(Fs,xs,NA,NQ);
print("a = ", vector(10,i,a[i]));
ker=fitrecR(a,2,3); P=normPR(vector(3,j,sum(e=0,3,ker[(j-1)*4+e+1,1]*x^e)));
print("P0 = ", P[1]); print("P1 = ", P[2]); print("P2 = ", P[3]);
print("charpoly = ", sum(j=1,3, polcoeff(P[j],3)*y^(j-1)));
print("freeint = ", freetest(a,70));
aa=iterrec2(P,a[1],a[2],NB); bb=iterrec2(P,0,1,NB);
rep=1; for(i=1,min(#a,50), if(aa[i]!=a[i], rep=0; break)); print("reproduces = ", rep);
print("k = ", denexp(bb,150));
xi = bb[NB]*1.0/aa[NB]; print("xi  = ", xi);
print("xi' = ", bb[NB-1]*1.0/aa[NB-1]);

print("### N=",9," C=",27," B=",9," deg=",1," r=",[-3, 0, 3]);
dv=[1, 3, 9]; r=[-3, 0, 3]; C=27; B=9;
us=useries(dv,r,NQ); Fs=Fseries(dv,r,NQ); xs=us/(1+B*us+C*us^2);
a=peel2(Fs,xs,NA,NQ);
print("a = ", vector(10,i,a[i]));
ker=fitrecR(a,2,3); P=normPR(vector(3,j,sum(e=0,3,ker[(j-1)*4+e+1,1]*x^e)));
print("P0 = ", P[1]); print("P1 = ", P[2]); print("P2 = ", P[3]);
print("charpoly = ", sum(j=1,3, polcoeff(P[j],3)*y^(j-1)));
print("freeint = ", freetest(a,70));
aa=iterrec2(P,a[1],a[2],NB); bb=iterrec2(P,0,1,NB);
rep=1; for(i=1,min(#a,50), if(aa[i]!=a[i], rep=0; break)); print("reproduces = ", rep);
print("k = ", denexp(bb,150));
xi = bb[NB]*1.0/aa[NB]; print("xi  = ", xi);
print("xi' = ", bb[NB-1]*1.0/aa[NB-1]);

print("### N=",10," C=",25," B=",6," deg=",2," r=",[-2, -2, 2, 2]);
dv=[1, 2, 5, 10]; r=[-2, -2, 2, 2]; C=25; B=6;
us=useries(dv,r,NQ); Fs=Fseries(dv,r,NQ); xs=us/(1+B*us+C*us^2);
a=peel2(Fs,xs,NA,NQ);
print("a = ", vector(10,i,a[i]));
ker=fitrecR(a,2,3); P=normPR(vector(3,j,sum(e=0,3,ker[(j-1)*4+e+1,1]*x^e)));
print("P0 = ", P[1]); print("P1 = ", P[2]); print("P2 = ", P[3]);
print("charpoly = ", sum(j=1,3, polcoeff(P[j],3)*y^(j-1)));
print("freeint = ", freetest(a,70));
aa=iterrec2(P,a[1],a[2],NB); bb=iterrec2(P,0,1,NB);
rep=1; for(i=1,min(#a,50), if(aa[i]!=a[i], rep=0; break)); print("reproduces = ", rep);
print("k = ", denexp(bb,150));
xi = bb[NB]*1.0/aa[NB]; print("xi  = ", xi);
print("xi' = ", bb[NB-1]*1.0/aa[NB-1]);

print("### N=",12," C=",9," B=",10," deg=",2," r=",[-4, 4, 4, -4, -4, 4]);
dv=[1, 2, 3, 4, 6, 12]; r=[-4, 4, 4, -4, -4, 4]; C=9; B=10;
us=useries(dv,r,NQ); Fs=Fseries(dv,r,NQ); xs=us/(1+B*us+C*us^2);
a=peel2(Fs,xs,NA,NQ);
print("a = ", vector(10,i,a[i]));
ker=fitrecR(a,2,3); P=normPR(vector(3,j,sum(e=0,3,ker[(j-1)*4+e+1,1]*x^e)));
print("P0 = ", P[1]); print("P1 = ", P[2]); print("P2 = ", P[3]);
print("charpoly = ", sum(j=1,3, polcoeff(P[j],3)*y^(j-1)));
print("freeint = ", freetest(a,70));
aa=iterrec2(P,a[1],a[2],NB); bb=iterrec2(P,0,1,NB);
rep=1; for(i=1,min(#a,50), if(aa[i]!=a[i], rep=0; break)); print("reproduces = ", rep);
print("k = ", denexp(bb,150));
xi = bb[NB]*1.0/aa[NB]; print("xi  = ", xi);
print("xi' = ", bb[NB-1]*1.0/aa[NB-1]);

print("### N=",12," C=",1," B=",34," deg=",4," r=",[-12, 24, 12, -12, -24, 12]);
dv=[1, 2, 3, 4, 6, 12]; r=[-12, 24, 12, -12, -24, 12]; C=1; B=34;
us=useries(dv,r,NQ); Fs=Fseries(dv,r,NQ); xs=us/(1+B*us+C*us^2);
a=peel2(Fs,xs,NA,NQ);
print("a = ", vector(10,i,a[i]));
ker=fitrecR(a,2,3); P=normPR(vector(3,j,sum(e=0,3,ker[(j-1)*4+e+1,1]*x^e)));
print("P0 = ", P[1]); print("P1 = ", P[2]); print("P2 = ", P[3]);
print("charpoly = ", sum(j=1,3, polcoeff(P[j],3)*y^(j-1)));
print("freeint = ", freetest(a,70));
aa=iterrec2(P,a[1],a[2],NB); bb=iterrec2(P,0,1,NB);
rep=1; for(i=1,min(#a,50), if(aa[i]!=a[i], rep=0; break)); print("reproduces = ", rep);
print("k = ", denexp(bb,150));
xi = bb[NB]*1.0/aa[NB]; print("xi  = ", xi);
print("xi' = ", bb[NB-1]*1.0/aa[NB-1]);

print("### N=",18," C=",1," B=",14," deg=",4," r=",[-6, 6, 12, -12, -6, 6]);
dv=[1, 2, 3, 6, 9, 18]; r=[-6, 6, 12, -12, -6, 6]; C=1; B=14;
us=useries(dv,r,NQ); Fs=Fseries(dv,r,NQ); xs=us/(1+B*us+C*us^2);
a=peel2(Fs,xs,NA,NQ);
print("a = ", vector(10,i,a[i]));
ker=fitrecR(a,2,3); P=normPR(vector(3,j,sum(e=0,3,ker[(j-1)*4+e+1,1]*x^e)));
print("P0 = ", P[1]); print("P1 = ", P[2]); print("P2 = ", P[3]);
print("charpoly = ", sum(j=1,3, polcoeff(P[j],3)*y^(j-1)));
print("freeint = ", freetest(a,70));
aa=iterrec2(P,a[1],a[2],NB); bb=iterrec2(P,0,1,NB);
rep=1; for(i=1,min(#a,50), if(aa[i]!=a[i], rep=0; break)); print("reproduces = ", rep);
print("k = ", denexp(bb,150));
xi = bb[NB]*1.0/aa[NB]; print("xi  = ", xi);
print("xi' = ", bb[NB-1]*1.0/aa[NB-1]);

quit;
