/* 17_allsub.gp -- ALL genus-0 quotients X_0(N)/W_S for EVERY subgroup S of the
   Atkin-Lehner group (not only those generated by prime-power involutions),
   N <= 60, with orbifold defect A and cusp-orbit count. Fixes the gap in 01_groups.gp. */
default(parisizemax, 6000000000);
idx(n) = my(f=factor(n)~); n*prod(i=1,#f, 1+1/f[1,i]);
nu2(n) = if(n%4==0, 0, my(f=factor(n)[,1]~); prod(i=1,#f, 1 + kronecker(-4, f[i])));
nu3(n) = if(n%9==0, 0, my(f=factor(n)[,1]~); prod(i=1,#f, 1 + kronecker(-3, f[i])));
ncusp0(n) = sumdiv(n, d, eulerphi(gcd(d,n/d)));
almat(n,qq) = my(d=bezout(qq,n/qq)); [qq*d[1], 1; -n*d[2], qq];
cusplist(n) = my(res=List()); fordiv(n,c, my(g=gcd(c,n/c), seen=List()); for(a=1, max(g,1), if(gcd(a,g)==1, my(new=1); for(k=1,#seen, if((a-seen[k])%g==0, new=0; break)); if(new, listput(seen,a); listput(res,[a,c]))))); Vec(res);
cuspeq(n,p1,p2) = (p1[1]*p2[2] - p2[1]*p1[2]) % gcd(p1[2]*p2[2], n) == 0;
cuspact(n,qq,p) = my(w=almat(n,qq)); my(a=w[1,1]*p[1]+w[1,2]*p[2], c=w[2,1]*p[1]+w[2,2]*p[2]); my(g=gcd(a,c)); if(g!=0, a/=g; c/=g); if(c<0, a=-a; c=-c); if(c==0, [1,0], [a,c]);
norbits(n, invs) = my(cl=cusplist(n), nc=#cl, lab=vector(nc,i,i)); for(i=1,nc, for(j=1,#invs, my(im=cuspact(n,invs[j],cl[i])); for(k=1,nc, if(cuspeq(n,im,cl[k]), my(o1=lab[i],o2=lab[k],m=min(o1,o2)); for(z=1,nc, if(lab[z]==o1||lab[z]==o2, lab[z]=m)); break)))); #Set(Vec(lab));
print("N|S(all AL elts)|mu'|ncuspQ|A|nu2|nu3");
{for(nn=1,60,
  my(mf=mfinit([nn,2],1), d=mfdim(mf));
  my(gens = select(q->(q>1 && isprimepower(q) && gcd(q,nn/q)==1), divisors(nn)));
  my(rr = #gens);
  my(mats = vector(rr, i, if(d>0, my(al=mfatkininit(mf,gens[i])); al[2]/al[3], matrix(0,0))));
  /* element index e in 0..2^rr-1 -> Q(e) = prod gens over set bits ; matrix M(e) */
  my(Qof = vector(2^rr, e, my(p=1); for(j=1,rr, if(bittest(e-1,j-1), p*=gens[j])); p));
  my(Mof = vector(2^rr, e, if(d==0, matrix(0,0), my(m=matid(d)); for(j=1,rr, if(bittest(e-1,j-1), m=m*mats[j])); m)));
  my(seen = List());
  /* enumerate subgroups: spans of subsets of size <= rr of nonzero elements */
  my(subs = List()); listput(subs, [0]);
  for(mask=1, 2^(2^rr-1)-1,
    if(hammingweight(mask) > rr, next);
    my(gg = List()); for(e=1, 2^rr-1, if(bittest(mask, e-1), listput(gg, e)));
    /* span */
    my(sp = List()); listput(sp, 0);
    for(t=1,#gg, my(cur=Vec(sp)); for(z=1,#cur, my(nw = bitxor(cur[z], gg[t])); my(f=0); for(w=1,#sp, if(sp[w]==nw, f=1; break)); if(!f, listput(sp, nw))));
    my(sv = vecsort(Vec(sp)));
    my(f=0); for(w=1,#subs, if(subs[w]==sv, f=1; break));
    if(!f, listput(subs, sv)));
  for(si=1,#subs,
    my(sv = subs[si], ww = #sv);
    my(g);
    if(d==0, g=0, my(P=matid(d)); for(z=1,#sv, if(sv[z]!=0, P = P*(matid(d)+Mof[sv[z]+1])/2)); g=matrank(P));
    if(g==0,
      my(mup = idx(nn)/ww);
      my(invs = List()); for(z=1,#sv, if(sv[z]!=0, listput(invs, Qof[sv[z]+1])));
      my(ncq = norbits(nn, Vec(invs)));
      my(A = mup/6 + 2 - ncq);
      print(nn,"|",Vec(invs),"|",mup,"|",ncq,"|",A,"|",nu2(nn),"|",nu3(nn))));
);}
quit;
