default(parisizemax, 10000000000);
default(realprecision, 140);
NQ = 100; NA = 74;
ps4(n) = if(n%5==0, 0, if(n%5==1, 1, if(n%5==2, I, if(n%5==3, -I, -1))));
ps4b(n) = conj(ps4(n));
one(n) = 1;
leg5(n) = kronecker(n,5);
xser(nq) = q*prod(n=1, nq-1, (1 - q^n + O(q^nq))^(5*leg5(n)));
Ap(n) = sum(k=0,n, binomial(n,k)^2*binomial(n+k,k));
eis(ch1, ch2, nq) = sum(n=1, nq-1, sumdiv(n, d, ch1(n/d)*ch2(d)*d^2)*q^n) + O(q^nq);
thq(s) = my(n=serprec(s,q)); sum(k=0,n-1, k*polcoeff(s,k)*q^k) + O(q^n);
Dinv2(s) = my(n=serprec(s,q)); sum(k=1,n-1, polcoeff(s,k)/k^2*q^k) + O(q^n);
peel2(Fs, xs, na, nq) = my(a=vector(na+1), G=Fs, xp=1+O(q^nq)); for(n=0, na, my(c=polcoeff(G,n)); a[n+1]=c; if(c!=0, G=G-c*xp); xp=xp*xs); a;
xs = xser(NQ);
Fs = sum(n=0, NA, Ap(n)*xs^n) + O(q^NQ);
A = peel2(Fs, xs, NA, NQ);
print("A = ", vector(8,i,A[i]));
PhiD = Fs*thq(xs);
print("Phi_D = F*theta_q(x) = ", vector(9,i,polcoeff(PhiD,i-1)));
print("table D c(m) = ", vector(9,i,if(i==1,0,sumdiv(i-1,d, (real(ps4(d))-2*imag(ps4(d)))*d^2))));
/* the four Eisenstein directions */
P1 = eis(one, ps4, NQ);   P2 = eis(one, ps4b, NQ);
P3 = eis(ps4, one, NQ);   P4 = eis(ps4b, one, NQ);
print("Phi3+Phi4 = ", vector(9,i,polcoeff(P3+P4,i-1)));
print("i(Phi3-Phi4) = ", vector(9,i,polcoeff(I*(P3-P4),i-1)));
lim(Ph, nm) = my(Th=Dinv2(Ph)); my(yB=Fs*Th); my(B=peel2(yB, xs, NA, NQ)); print(nm,":  xi = ", B[NA]*1.0/A[NA], "   (prev ", B[NA-1]*1.0/A[NA-1], ")");
lim(PhiD, "Phi_D (Zagier D source)");
lim(P3+P4, "Phi3+Phi4 (inner, real part)");
lim(I*(P3-P4), "i(Phi3-Phi4) (inner, imag part)");
lim(P1+P2, "Phi1+Phi2 (outer, real)");
lim(I*(P1-P2), "i(Phi1-Phi2) (outer, imag)");
Lchi(ch, s) = 5^(-s)*sum(a=1,4, ch(a)*zetahurwitz(s, a/5));
print("zeta(2)   = ", zeta(2));
print("zeta(2)/5 = ", zeta(2)/5);
print("L(2,psi4) = ", Lchi(ps4,2));
print("Re L(2,psi4) = ", real(Lchi(ps4,2)));
print("Im L(2,psi4) = ", imag(Lchi(ps4,2)));
print("L(2,chi5) = ", Lchi(x->kronecker(x,5), 2));
quit;
