default(parisizemax, 10000000000);
default(realprecision, 140);
NQ = 110; NA = 86;
ps4(n) = if(n%5==0, 0, if(n%5==1, 1, if(n%5==2, I, if(n%5==3, -I, -1))));
ps4b(n) = conj(ps4(n));
one(n) = 1;
leg5(n) = kronecker(n,5);
xser(nq) = q*prod(n=1, nq-1, (1 - q^n + O(q^nq))^(5*leg5(n)));
Ap(n) = sum(k=0,n, binomial(n,k)^2*binomial(n+k,k));
eis(ch1, ch2, nq) = sum(n=1, nq-1, sumdiv(n, d, ch1(n/d)*ch2(d)*d^2)*q^n) + O(q^nq);
Dinv2(s) = my(n=serprec(s,q)); sum(k=1,n-1, polcoeff(s,k)/k^2*q^k) + O(q^n);
peel2(Fs, xs, na, nq) = my(a=vector(na+1), G=Fs, xp=1+O(q^nq)); for(n=0, na, my(c=polcoeff(G,n)); a[n+1]=c; if(c!=0, G=G-c*xp); xp=xp*xs); a;
xs = xser(NQ); Fs = sum(n=0, NA, Ap(n)*xs^n) + O(q^NQ); A = peel2(Fs, xs, NA, NQ);
P1=eis(one,ps4,NQ); P2=eis(one,ps4b,NQ); P3=eis(ps4,one,NQ); P4=eis(ps4b,one,NQ);
R = [P1+P2, I*(P1-P2), P3+P4, I*(P3-P4)];
print("R1 = ", vector(8,i,polcoeff(R[1],i-1)));
print("R2 = ", vector(8,i,polcoeff(R[2],i-1)));
print("R3 = ", vector(8,i,polcoeff(R[3],i-1)));
print("R4 = ", vector(8,i,polcoeff(R[4],i-1)));
U = vector(4, j, my(B=peel2(Fs*Dinv2(R[j]), xs, NA, NQ)); vector(NA+1, i, real(B[i]*1.0/A[i])));
dd(j,n) = U[j][n+1]-U[j][n];
M = matrix(3,4, i,j, dd(j, NA-i+1));
print("difference matrix rows (n=",NA,",",NA-1,",",NA-2,"):");
for(i=1,3, print("  ", vector(4,j,M[i,j])));
print("Phi_D = R1/2 + R2 check: d_n = ", dd(1,NA)/2 + dd(2,NA));
K = matker(M);  print("numerical kernel dim: ", matsize(K)[2]);
/* solve for the fold-regular space: rank of M */
print("singular-ish: ratios of columns d_n^{(j)}/d_{n-1}^{(j)} = ", vector(4,j, dd(j,NA)/dd(j,NA-1)));
/* two-parameter search: R3 + a R1 + b R2 fold-regular? solve 2x2 from n=NA, NA-1 */
S = [[dd(1,NA), dd(2,NA)], [dd(1,NA-1), dd(2,NA-1)]];
rhs = [-dd(3,NA), -dd(3,NA-1)]~;
sol = matsolve(Mat([[dd(1,NA),dd(2,NA)],[dd(1,NA-1),dd(2,NA-1)]]~)~, rhs);
print("solve R3 + a R1 + b R2 fold-regular: (a,b) = ", sol);
cand = R[3] + sol[1]*R[1] + sol[2]*R[2];
Bc = peel2(Fs*Dinv2(cand), xs, NA, NQ);
print("candidate xi_n   = ", real(Bc[NA+1]/A[NA+1]*1.0));
print("candidate xi_n-1 = ", real(Bc[NA]/A[NA]*1.0));
print("candidate xi_n-2 = ", real(Bc[NA-1]/A[NA-1]*1.0));
Lchi(ch, s) = 5^(-s)*sum(a=1,4, ch(a)*zetahurwitz(s, a/5));
print("zeta(2)=",zeta(2), "  ReL(2,psi4)=", real(Lchi(ps4,2)), "  ImL(2,psi4)=", imag(Lchi(ps4,2)));
quit;
