default(parisizemax, 10000000000);
default(realprecision, 150);
NQ = 130; NA = 100;
ps4(n) = if(n%5==0, 0, if(n%5==1, 1, if(n%5==2, I, if(n%5==3, -I, -1))));
ps4b(n) = conj(ps4(n));
one(n) = 1;
leg5(n) = kronecker(n,5);
xser(nq) = q*prod(n=1, nq-1, (1 - q^n + O(q^nq))^(5*leg5(n)));
Ap(n) = sum(k=0,n, binomial(n,k)^2*binomial(n+k,k));
eis(ch1, ch2, nq) = sum(n=1, nq-1, sumdiv(n, d, ch1(n/d)*ch2(d)*d^2)*q^n) + O(q^nq);
Dinv2(s) = my(n=serprec(s,q)); sum(k=1,n-1, polcoeff(s,k)/k^2*q^k) + O(q^n);
peel2(Fs, xs, na, nq) = my(a=vector(na+1), G=Fs, xp=1+O(q^nq)); for(n=0, na, my(c=polcoeff(G,n)); a[n+1]=c; if(c!=0, G=G-c*xp); xp=xp*xs); a;
xs = xser(NQ); Fs = sum(n=0, NA, Ap(n)*xs^n) + O(q^NQ); A = peel2(Fs, xs, NA, NQ);
P3=eis(ps4,one,NQ); P4=eis(ps4b,one,NQ);
R3 = P3+P4; R4 = I*(P3-P4);
ph5 = (11+5*sqrt(5))/2;
cand = R3 + ph5*R4;
print("R3 = ", vector(10,i,polcoeff(R3,i-1)));
print("R4 = ", vector(10,i,polcoeff(R4,i-1)));
Bc = peel2(Fs*Dinv2(cand), xs, NA, NQ);
xi1 = real(Bc[NA+1]/A[NA+1]*1.0); xi2 = real(Bc[NA]/A[NA]*1.0); xi3 = real(Bc[NA-1]/A[NA-1]*1.0);
print("xi (n=",NA,")   = ", xi1);
print("xi (n=",NA-1,") = ", xi2);
print("xi (n=",NA-2,") = ", xi3);
print("digits of agreement n vs n-1: ", -log(abs(xi1-xi2)+1e-300)/log(10));
Lchi(ch, s) = 5^(-s)*sum(a=1,4, ch(a)*zetahurwitz(s, a/5));
LR = real(Lchi(ps4,2)); LI = imag(Lchi(ps4,2));
print("Re L(2,psi4) = ", LR);  print("Im L(2,psi4) = ", LI);
print("predicted -(ReL - phi^5 ImL) = ", -(LR - ph5*LI));
print("xi / that = ", xi1/(-(LR - ph5*LI)));
print("lindep [xi, 1, zeta(2), ReL, ImL, sqrt5, sqrt5*ReL, sqrt5*ImL]:");
print(lindep([xi1, 1, zeta(2), LR, LI, sqrt(5), sqrt(5)*LR, sqrt(5)*LI], 40));
print("lindep [xi, ReL, ImL, sqrt5*ReL, sqrt5*ImL]: ", lindep([xi1, LR, LI, sqrt(5)*LR, sqrt(5)*LI], 40));
print("lindep [xi, ReL, ImL]: ", lindep([xi1, LR, LI], 40));
quit;
