default(parisizemax, 10000000000);
NQ = 95; NA = 76;
ps4(n) = if(n%5==0, 0, if(n%5==1, 1, if(n%5==2, I, if(n%5==3, -I, -1))));
ps4b(n) = conj(ps4(n));
one(n) = 1;
leg5(n) = kronecker(n,5);
xser(nq) = q*prod(n=1, nq-1, (1 - q^n + O(q^nq))^(5*leg5(n)));
Ap(n) = sum(k=0,n, binomial(n,k)^2*binomial(n+k,k));
eisI(ch1, ch2, nq) = sum(n=1, nq-1, sumdiv(n, d, ch1(n/d)*ch2(d)*d^2)*q^n) + O(q^nq);
Dinv2(s) = my(n=serprec(s,q)); sum(k=1,n-1, polcoeff(s,k)/k^2*q^k) + O(q^n);
peel2(Fs, xs, na, nq) = my(a=vector(na+1), G=Fs, xp=1+O(q^nq)); for(n=0, na, my(c=polcoeff(G,n)); a[n+1]=c; if(c!=0, G=G-c*xp); xp=xp*xs); a;
realser(s, nq) = sum(k=0,nq-1, real(polcoeff(s,k))*q^k) + O(q^nq);
xs = xser(NQ); Fs = sum(n=0, NA, Ap(n)*xs^n) + O(q^NQ); A = peel2(Fs, xs, NA, NQ);
P3=eisI(ps4,one,NQ); P4=eisI(ps4b,one,NQ);
R3 = realser(P3+P4, NQ); R4 = realser(I*(P3-P4), NQ);
denexp(bb, nn) = my(dn=1, km=0); for(n=1, nn, dn=lcm(dn,n); my(bn=bb[n+1]); if(bn!=0, my(de=denominator(bn), kj=0, t=de); while(t>1 && kj<12, kj++; t=t/gcd(t,dn)); if(kj>km, km=kj))); km;
kof(Ph, nm) = my(B = peel2(Fs*Dinv2(Ph), xs, NA, NQ)); print(nm, ": B_1..B_6 = ", vector(6,i,B[i+1]), "   k = ", denexp(B, NA));
kof(R3, "R3 = Phi3+Phi4      ");
kof(R4, "R4 = i(Phi3-Phi4)   ");
kof(2*R3+11*R4, "2R3+11R4 (rational part)");
kof(5*R4, "5R4 (sqrt5 part)   ");
PD = realser(eisI(one,ps4,NQ)+eisI(one,ps4b,NQ), NQ)/2 + realser(I*(eisI(one,ps4,NQ)-eisI(one,ps4b,NQ)), NQ);
kof(PD, "Phi_D (control)     ");
quit;
