read("common.gp");
default(realprecision,40);
print(ROWS[1]);
print("c(m) gamma m=1..8: ", vector(8,m,cm("gamma",m)));
print("target gamma: ", Ltarget("gamma"), "  zeta(3)/6=", zeta(3)/6);
print("target delta: ", Ltarget("delta"), "  13z3/54=", 13*zeta(3)/54);
print("target A: ", Ltarget("A"), " zeta(2)/4=",zeta(2)/4);
print("target D: ", Ltarget("D"), " zeta(2)/5=",zeta(2)/5);
print("target eta: ", Ltarget("eta"), " L(5,3)/2=",lfun(5,3)/2);
quit;
