default(parisizemax, 6000000000);
LOG = "/home/ubuntu/code/math-modular-sources/lattice/multislope/row2_lindep.log";
W(s) = write(LOG, s);
read("/home/ubuntu/code/math-modular-sources/lattice/multislope/row2_data.txt");
rB = R2X1/R2A; rC = R2X2/R2A; rD = R2X3/R2A;
W(Str("=== AESZ207 2-adic lindep, data at N = ", NB2, " ==="));
W(Str("  v_2(rB)=",valuation(rB,2),"  v_2(rC)=",valuation(rC,2),"  v_2(rD)=",valuation(rD,2)));
PRE = 19000;
xB = rB + O(2^PRE); xC = rC + O(2^PRE); xD = rD + O(2^PRE);
W(Str("  16*xi_2(B) mod 2^40 = ", lift(16*rB + O(2^40))));
W(Str("  16*xi_2(C) mod 2^40 = ", lift(16*rC + O(2^40))));
W(Str("  256*xi_2(D) mod 2^40 = ", lift(256*rD + O(2^40))));
W(Str("  16*xi_2(B) mod 2^120 = ", lift(16*rB + O(2^120))));
W(Str("  16*xi_2(C) mod 2^120 = ", lift(16*rC + O(2^120))));
W(Str("  256*xi_2(D) mod 2^120 = ", lift(256*rD + O(2^120))));
W("");
hgt(v) = { my(m=0); for(i=1,#v, m = max(m, #Str(abs(v[i])))); m };
W("--- 2-adic lindep (heights reported as max #decimal digits of the coefficients) ---");
tst(nm, v) = { my(L = lindep(v)); W(Str("  ", nm, "  -> max coeff size ", hgt(L), " digits;  coeffs = ", if(hgt(L)<40, L, "[huge]"))); if(hgt(L)<40, W(Str("      residual v_2 = ", valuation(sum(i=1,#v, L[i]*v[i]),2)))); L };
tst("[1,xiB,xiC,xiD]", [1+O(2^PRE), xB, xC, xD]);
tst("[1,xiB,xiC]    ", [1+O(2^PRE), xB, xC]);
tst("[1,xiB,xiD]    ", [1+O(2^PRE), xB, xD]);
tst("[1,xiC,xiD]    ", [1+O(2^PRE), xC, xD]);
tst("[xiB,xiC,xiD]  ", [xB, xC, xD]);
tst("[1,xiB]        ", [1+O(2^PRE), xB]);
tst("[xiB,xiC]      ", [xB, xC]);
tst("[xiB,xiD]      ", [xB, xD]);
tst("[xiC,xiD]      ", [xC, xD]);
W("");
W(Str("  xiC/xiB mod 2^60 = ", (rC/rB) + O(2^60)));
W(Str("  xiD/xiB mod 2^60 = ", (rD/rB) + O(2^60)));
W("");
W("--- with sqrt(17) adjoined (Q(sqrt17) coefficients) ---");
s17 = sqrt(17 + O(2^PRE));
tst("[1,s17,xiB,s17*xiB]", [1+O(2^PRE), s17, xB, s17*xB]);
tst("[xiB,s17*xiB,xiC,s17*xiC]", [xB, s17*xB, xC, s17*xC]);
W("DONE");
quit;
