default(parisizemax, 6000000000);
default(realprecision,60);
ciB = read("/home/ubuntu/code/math-modular-sources/lattice/multislope/row4_recB.txt");
ciA = read("/home/ubuntu/code/math-modular-sources/lattice/multislope/row4_recA.txt");
getQ(ci, r, D) = vector(r+1, k, my(i=k-1); sum(j=0,D, ci[i*(D+1)+j+1]*'n^j));
QB = getQ(ciB, 35, 7);
QA = getQ(ciA, 22, 23);
chi(ci, r, D) = sum(i=0,r, ci[i*(D+1)+D+1]*'x^(r-i));
chB = chi(ciB, 35, 7);
chA = chi(ciA, 22, 23);
print("### shape B (r=35,D=7)");
print("content(chB) = ", content(chB));
chB = chB/content(chB);
print("chB = ", chB);
print("deg = ", poldegree(chB));
print("factor:"); print(factor(chB));
print("roots (floating): "); print(polroots(chB));
print("product of roots = (-1)^deg * const/lead = ", (-1)^poldegree(chB)*polcoeff(chB,0)/pollead(chB));
print("");
print("### shape A (r=22,D=23)");
print("content(chA) = ", content(chA));
chA = chA/content(chA);
print("chA = ", chA);
print("deg = ", poldegree(chA));
print("factor:"); print(factor(chA));
print("roots (floating): "); print(polroots(chA));
print("product of roots = ", (-1)^poldegree(chA)*polcoeff(chA,0)/pollead(chA));
print("");
print("Q_0 (shape B) = ", QB[1]);
print("Q_35 (shape B) = ", QB[36]);
print("Q_0 (shape A) = ", QA[1]);
print("Q_22 (shape A) = ", QA[23]);
write("/home/ubuntu/code/math-modular-sources/lattice/multislope/row4_QB.txt", QB);
write("/home/ubuntu/code/math-modular-sources/lattice/multislope/row4_QA.txt", QA);
quit
