/* hosts.gp -- genus-zero hosts: Gamma_0(N) and Atkin-Lehner quotients, N<=60.
   genus(X_0(N))            = dim S_2(Gamma_0(N))
   genus(X_0(N)/W_S)        = dim of the subspace of S_2 fixed by all w_Q, Q in S.
   Also: number of cusps, elliptic points e2,e3, index.
   Output: hosts.txt  (one line per (N, AL-subgroup)) */

default(parisize, 800000000);

nu2(N) = if(N%4==0, 0, prod(i=1,#(f=factor(N)~), my(p=f[1,i]); if(p==2,1,1+kronecker(-1,p))));
nu3(N) = if(N%9==0, 0, prod(i=1,#(f=factor(N)~), my(p=f[1,i]); if(p==3,1,1+kronecker(-3,p))));
ncusps(N) = sumdiv(N, d, eulerphi(gcd(d,N/d)));
idx(N) = N*prod(i=1,#(f=factor(N)~), 1+1/f[1,i]);

/* exact Atkin-Lehner divisors Q || N, Q>1 */
ALdivs(N) = my(f=factor(N), L=List()); forvec(v=vector(#f~,i,[0,1]), my(Q=prod(i=1,#f~, f[i,1]^(v[i]*f[i,2]))); if(Q>1, listput(L,Q))); Vec(L);

{
w = fileopen("lattice/cdt_finder/hosts.txt","w");
filewrite(w, "# N  ALsubgroup(space-sep Q's, '-'=trivial)  genus  ncusps_upstairs  e2  e3  index");
for(N=1,60,
  my(g0, mf, S, dimS, als, subs);
  mf = mfinit([N,2],1);   /* cuspidal newspace? 1 = cuspidal full space */
  S = mfdim(mf);
  g0 = S;
  filewrite(w, Str(N," -  ",g0,"  ",ncusps(N),"  ",nu2(N),"  ",nu3(N),"  ",idx(N)));
  als = ALdivs(N);
  if(#als>0 && S<=40,
    /* all subgroups generated by subsets of the AL divisors: enumerate subsets of the prime-power AL gens */
    my(f=factor(N), gens=vector(#f~,i,f[i,1]^f[i,2]));
    forvec(v=vector(#gens,i,[0,1]),
      my(sel=[], Qs=List());
      for(i=1,#gens, if(v[i]==1, listput(Qs,gens[i])));
      Qs=Vec(Qs);
      if(#Qs>0,
        my(M = matid(S), ok=1);
        for(j=1,#Qs,
          my(A);
          A = mfatkininit(mf,Qs[j]);
          if(A==0, ok=0; break);
          M = M*0; /* placeholder */
        );
      );
    );
  );
);
fileclose(w);
}
quit;
