import csv
from math import gcd, log, log2
def v2(x):
    x=abs(x); return None if x==0 else (x&-x).bit_length()-1
Z={int(r['n']):(int(r['X_n']),int(r['Y_n'])) for r in csv.DictReader(open('zudilin_rows.csv'))}
N={int(r['n']):(int(r['V_n']),int(r['U_n'])) for r in csv.DictReader(open('nesterenko_rows.csv'))}
D={}; cur=1
for i in range(1,600): cur=cur*i//gcd(cur,i); D[i]=cur
print("  n | log2 S/n | log2 T/n | log2(ST)/n | TRUE log2 index/n | sigma nats | F=(E1+E2-sig)/2")
E1E2=13.0+14.21
for n in (20,40,60,80,98):
    X,Y=Z[n]; V,U=N[n]; S=D[6*n]**2
    a1,a2=X//S,V//S
    h=a1*U-a2*Y; T=1<<v2(h); M=S*T
    # covol of lattice generated by (a1,Y),(a2,U),(T,0),(0,M)  = gcd of all 2x2 minors
    g=0
    for m in (h, T*Y, a1*M, T*U, a2*M, T*M):
        g=gcd(g,abs(m))
    idx=(T*M)//g
    print("  %3d | %8.3f | %8.3f | %10.3f | %17.3f | %10.3f | %+.4f"%(
        n, log2(S)/n, log2(T)/n, log2(M)/n, log2(idx)/n, log(idx)/n, (E1E2-log(idx)/n)/2))
